name: Build and Push to Docker hub

on:
  release:
    types: 
      - published
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.IMAGE_TAG }}:${{ github.event.release.tag_name }}
      
      - name: Clone config repo
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: utibeabasi6/argocd-config
          path: argocd-config
          
      - name: Replace tag
        run: |
          cd argocd-config/dev
          sed s/${{secrets.PREVIOUS_RELEASE}}/${{ github.event.release.tag_name }}/g > deployment.yaml
          git config --global user.email "utibeabasiumanah6@gmail.com"
          git config --global user.name "utibeabasi6"
          git commit -am "Update deployment: GHA" && cd ../..
      
      - name: Push config to repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: utibeabasi6/argocd-config
          directory: argocd-config
          
      - name: Update previous release
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'PREVIOUS_RELEASE'
          value: ${{ github.event.release.tag_name }}
          repository: utibeabasi6/argocd-source-code
          token: ${{ secrets.REPO_ACCESS_TOKEN }}


